apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: longhorn-admission-webhook
  namespace: longhorn-system
spec:
  podSelector:
    matchLabels:
      longhorn.io/admission-webhook: longhorn-admission-webhook
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 9502
