{{- if .Values.privateRegistry.createSecret }}
{{- if .Values.privateRegistry.registrySecret }}
{{- if not (kindIs "string" .Values.privateRegistry.registrySecret) }}
{{- fail "The privateRegistry.registrySecret value must be a string" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.privateRegistry.registrySecret }}
  namespace: {{ include "release_namespace" . }}
  labels: {{- include "longhorn.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "secret" . }}
{{- end }}
{{- end }}
