{{- if and .Values.persistence.encryption.enabled (not .Values.persistence.encryption.secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: {{ include "release_namespace" . }}
data:
    {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "longhorn-crypto") | default dict }}
    {{- $secretData := (get $secretObj "data") | default dict }}
    {{- $passphrase := (get $secretData "CRYPTO_KEY_VALUE") | default (randAlphaNum 32 | b64enc) }}
    CRYPTO_KEY_VALUE: {{ $passphrase | quote }}
    CRYPTO_KEY_PROVIDER: {{ ( "secret" | b64enc ) }}
    CRYPTO_KEY_CIPHER: {{ ( "aes-xts-plain64" | b64enc ) }}
    CRYPTO_KEY_HASH: {{ ( "sha256" | b64enc ) }}
    CRYPTO_KEY_SIZE: {{ ( "256" | b64enc ) }}
    CRYPTO_PBKDF: {{ ( "argon2i" | b64enc ) }}
{{- end }}