kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-v2-replicated
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataEngine: "v2"
  # dataLayout is optional for replicated volumes - RAID1 is the default.
  dataLayout.type: "replicated"
  dataLayout.mode: "raid1"
  numberOfReplicas: "3"             # 3-way mirror; tolerates 2 replica failures
  staleReplicaTimeout: "2880"
  fsType: "ext4"
#  mkfsParams: "-I 256 -b 4096 -O ^metadata_csum,^64bit"
#  nodeSelector: "storage,fast"
#  recurringJobSelector: '[{"name":"snap-group", "isGroup":true},
#                          {"name":"backup", "isGroup":false}]'
#  fromBackup: ""
#  backingImage: "bi-test"
#  backingImageDataSourceType: "download"
#  backingImageDataSourceParameters: '{"url": "https://backing-image-example.s3-region.amazonaws.com/test-backing-image"}'
#  backingImageChecksum: "SHA512 checksum of the backing image"
#  unmapMarkSnapChainRemoved: "ignored"
#  diskSelector: "ssd,fast"
#  nfsOptions: "soft,timeo=150,retrans=3"
