name: Epic request
description: Suggest an Epic for grouped features, enhancements or tasks
title: "[EPIC] "
labels: [ "Epic" ]
assignees:
-
body:
- type: textarea
  attributes:
    label: Is your Epic request related to a problem? Please describe (👍 if you like this request)
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the tasks for this Epic
    description: A clear and concise description of what you want to happen. For each sub-task, please create the corresponding issues and connect them to this Epic.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    placeholder: Add any other context or screenshots about the feature request here.
  validations:
    required: false
