name: Improvement request
description: Suggest an improvement of an existing feature
title: "[IMPROVEMENT] "
labels: ["kind/improvement", "require/doc", "require/manual-test-plan", "require/backport"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for stopping by to let us know something could be better!

        For general questions or discussions, please use the [Discussions](https://github.com/longhorn/longhorn/discussions) tab.

  - type: textarea
    attributes:
      label: Is your improvement request related to a feature? Please describe (👍 if you like this request)
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
