kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-secure-per-volume-ns-longhorn-system
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  encrypted: "true"
  # The key is read during node staging/publishing, not volume provisioning.
  # Ensure the referenced Secret exists before starting a workload.
  csi.storage.k8s.io/node-publish-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
  # These two are for online expansion of encrypted volumes.
  csi.storage.k8s.io/node-expand-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-expand-secret-namespace: "longhorn-system"
