name: "[Issue Management] Add Issue To Projects"

on:
  issues:
    types: [opened, reopened, milestoned]

jobs:
  longhorn:
    runs-on: ubuntu-latest
    steps:
    - id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.LONGHORN_GITHUB_BOT_APP_ID }}
        private-key: ${{ secrets.LONGHORN_GITHUB_BOT_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        permission-contents: write
        permission-pull-requests: write
        permission-members: read
        permission-issues: write
        permission-organization-projects: write

    - name: Check Longhorn Membership (including bot)
      id: check-membership
      run: |
        if [[ "${{ github.event.issue.user.login }}" == "github-actions[bot]" ]]; then
          echo "is_longhorn_member=true" >> $GITHUB_ENV
        else
          echo "is_longhorn_member=false" >> $GITHUB_ENV
        fi

    - name: Real Membership Check (non-bot only)
      if: env.is_longhorn_member == 'false'
      id: is-longhorn-member
      continue-on-error: true
      uses: tspascoal/get-user-teams-membership@v3
      with:
        username: ${{ github.event.issue.user.login }}
        organization: longhorn
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Set Final Membership Flag
      if: env.is_longhorn_member == 'false' && fromJSON(steps.is-longhorn-member.outputs.teams)[0] != null
      run: echo "is_longhorn_member=true" >> $GITHUB_ENV

    - name: Debug Membership Status
      run: |
        echo "is_longhorn_member: ${{ env.is_longhorn_member }}"
        echo "teams: ${{ steps.is-longhorn-member.outputs.teams || 'bot or N/A' }}"
        echo "check outcome: ${{ steps.is-longhorn-member.outcome || 'bot or N/A' }}"

    - name: Add Issue to Longhorn Sprint Project
      if: env.is_longhorn_member == 'true'
      uses: actions/add-to-project@v1.0.2
      with:
        project-url: https://github.com/orgs/longhorn/projects/8
        github-token: ${{ steps.app-token.outputs.token }}
        labeled: kind/test
        label-operator: NOT

  community:
    runs-on: ubuntu-latest
    steps:
    - id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.LONGHORN_GITHUB_BOT_APP_ID }}
        private-key: ${{ secrets.LONGHORN_GITHUB_BOT_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        permission-contents: write
        permission-pull-requests: write
        permission-members: read
        permission-issues: write
        permission-organization-projects: write

    - name: Is Longhorn Member
      id: is-longhorn-member
      continue-on-error: true
      uses: tspascoal/get-user-teams-membership@v3
      with:
        username: ${{ github.event.issue.user.login }}
        organization: longhorn
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Get Issue
      if: steps.is-longhorn-member.outcome == 'success'
      uses: octokit/request-action@v2.x
      id: issue
      with:
        route: GET /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Add Issue to Community Sprint Project
      id: add-project
      if: |
        steps.is-longhorn-member.outcome == 'success' &&
        fromJSON(steps.is-longhorn-member.outputs.teams)[0] == null
      uses: actions/add-to-project@v1.0.2
      with:
        project-url: https://github.com/orgs/longhorn/projects/5
        github-token: ${{ steps.app-token.outputs.token }}

    - name: Update Item To New
      if: |
        steps.is-longhorn-member.outcome == 'success' &&
        fromJSON(steps.is-longhorn-member.outputs.teams)[0] == null &&
        steps.add-project.outputs.itemId != ''
      uses: titoportas/update-project-fields@v0.1.0
      with:
        project-url: https://github.com/orgs/longhorn/projects/5
        github-token: ${{ steps.app-token.outputs.token }}
        item-id: ${{ steps.add-project.outputs.itemId }}
        field-keys: Status,Sprint
        field-values: "New,[0]"

  qa:
    runs-on: ubuntu-latest
    steps:
    - id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.LONGHORN_GITHUB_BOT_APP_ID }}
        private-key: ${{ secrets.LONGHORN_GITHUB_BOT_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        permission-contents: write
        permission-pull-requests: write
        permission-members: read
        permission-issues: write
        permission-organization-projects: write

    - name: Is Longhorn Member
      id: is-longhorn-member
      uses: tspascoal/get-user-teams-membership@v3
      with:
        username: ${{ github.event.issue.user.login }}
        organization: longhorn
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Add Issue to QA Sprint Project
      if: fromJSON(steps.is-longhorn-member.outputs.teams)[0] != null
      uses: actions/add-to-project@v1.0.2
      with:
        project-url: https://github.com/orgs/longhorn/projects/4
        github-token: ${{ steps.app-token.outputs.token }}
        labeled: kind/test, area/infra
        label-operator: OR
