name: Periodic Issue Sprint Update

on:
  schedule:
    # Trigger every Sunday at 20:00
    - cron: '0 20 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  repository-projects: write
  issues: write 

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check sprint build is required
      id: check_sprint_build_required
      continue-on-error: true
      run: |
        python ./.github/workflows/check-sprint-last-day.py "longhorn" "longhorn" "Longhorn Sprint"

    - name: Longhorn Sprint Issues - Clear Sprint
      uses: derekbit/move-to-next-iteration@master
      if: steps.check_sprint_build_required.outcome == 'success'
      with:
        owner: longhorn
        number: 8
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        iteration-field: Sprint
        iteration: current
        new-iteration: none
        excluded-statuses: "Review,Ready For Testing,Testing,Closed"

    - name: Longhorn Sprint Issues - Move to Next Sprint
      uses: derekbit/move-to-next-iteration@master
      if: steps.check_sprint_build_required.outcome == 'success'
      with:
        owner: longhorn
        number: 8
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        iteration-field: Sprint
        iteration: current
        new-iteration: next
        statuses: "Review"

    - name: Longhorn Sprint Issues - Update None to Current Sprint
      if: steps.check_sprint_build_required.outcome == 'success'
      uses: derekbit/move-to-next-iteration@master
      with:
        owner: longhorn
        number: 8
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        iteration-field: Sprint
        iteration: none
        new-iteration: current
        statuses: "Ready For Testing"

    - name: QA Sprint - Clear Sprint
      uses: derekbit/move-to-next-iteration@master
      if: steps.check_sprint_build_required.outcome == 'success'
      with:
        owner: longhorn
        number: 4
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        iteration-field: Sprint
        iteration: current
        new-iteration: none
        excluded-statuses: "Review,Testing,Closed"

    - name: QA Sprint - Move to Next Sprint
      uses: derekbit/move-to-next-iteration@master
      if: steps.check_sprint_build_required.outcome == 'success'
      with:
        owner: longhorn
        number: 4
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        iteration-field: Sprint
        iteration: current
        new-iteration: next
        statuses: "Review"

    - name: Longhorn Community Sprint issues - Move to Next Sprint
      uses: derekbit/move-to-next-iteration@master
      if: steps.check_sprint_build_required.outcome == 'success'
      with:
        owner: longhorn
        number: 5
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        iteration-field: Sprint
        iteration: current
        new-iteration: next
        statuses: 'New'