name: "[Issue Management] Periodic Issue Sprint Update"

on:
  schedule:
    # Trigger every Sunday at 20:00
    - cron: '0 20 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  repository-projects: write
  issues: write 

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest
    
    steps:
    - id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.LONGHORN_GITHUB_BOT_APP_ID }}
        private-key: ${{ secrets.LONGHORN_GITHUB_BOT_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        permission-contents: write
        permission-pull-requests: write
        permission-issues: write
        permission-organization-projects: write

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check sprint build is required
      id: check_sprint_build_required
      continue-on-error: true
      run: |
        python ./.github/workflows/check-sprint-last-day.py "longhorn" "longhorn" "Longhorn Sprint"

    - name: Longhorn Sprint Issues - Clear Sprint
      uses: rancher/gh-issue-mgr/move-to-next-iteration@main
      if: steps.check_sprint_build_required.outcome == 'success'
      with:
        owner: longhorn
        number: 8
        token: ${{ steps.app-token.outputs.token }}
        iteration-field: Sprint
        iteration: current
        new-iteration: none
        excluded-statuses: "Review,Ready For Testing,Testing,Closed"

    - name: Longhorn Sprint Issues - Move to Next Sprint
      uses: rancher/gh-issue-mgr/move-to-next-iteration@main
      if: steps.check_sprint_build_required.outcome == 'success'
      with:
        owner: longhorn
        number: 8
        token: ${{ steps.app-token.outputs.token }}
        iteration-field: Sprint
        iteration: current
        new-iteration: next
        statuses: "Review"

    - name: Longhorn Sprint Issues - Update None to Current Sprint
      if: steps.check_sprint_build_required.outcome == 'success'
      uses: rancher/gh-issue-mgr/move-to-next-iteration@main
      with:
        owner: longhorn
        number: 8
        token: ${{ steps.app-token.outputs.token }}
        iteration-field: Sprint
        iteration: none
        new-iteration: current
        statuses: "Ready For Testing"

    - name: QA Sprint - Clear Sprint
      uses: rancher/gh-issue-mgr/move-to-next-iteration@main
      if: steps.check_sprint_build_required.outcome == 'success'
      with:
        owner: longhorn
        number: 4
        token: ${{ steps.app-token.outputs.token }}
        iteration-field: Sprint
        iteration: current
        new-iteration: none
        excluded-statuses: "Review,Testing,Closed"

    - name: QA Sprint - Move to Next Sprint
      uses: rancher/gh-issue-mgr/move-to-next-iteration@main
      if: steps.check_sprint_build_required.outcome == 'success'
      with:
        owner: longhorn
        number: 4
        token: ${{ steps.app-token.outputs.token }}
        iteration-field: Sprint
        iteration: current
        new-iteration: next
        statuses: "Review"

    - name: Longhorn Community Sprint issues - Move to Next Sprint
      uses: rancher/gh-issue-mgr/move-to-next-iteration@main
      if: steps.check_sprint_build_required.outcome == 'success'
      with:
        owner: longhorn
        number: 5
        token: ${{ steps.app-token.outputs.token }}
        iteration-field: Sprint
        iteration: current
        new-iteration: next
        statuses: 'New'