name: "[PR Management] Validate Longhorn YAMLs"

on:
  pull_request:
    types:
      - opened
      - edited 
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  validate-yamls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 1
          
      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint python3-venv
          
      - name: Create yamllint config
        run: |
          cat > .yamllint <<EOF
          extends: default
          
          rules:
            line-length: disable
            trailing-spaces: disable
            document-start: disable
            empty-lines: disable
          EOF
          
      - name: Validate YAML file
        run: yamllint -c .yamllint chart/questions.yaml

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.19.0

      - name: Test Helm chart
        run: |
          python3 -m venv .venv
          .venv/bin/python -m pip install -r chart/tests/requirements.txt
          .venv/bin/python -m unittest discover -s chart/tests -v
